site_name: Centrifugo
site_description: Centrifugo Documentation
site_author: containo.us
site_url: https://github.com/centrifugal/centrifugo
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/centrifugal/centrifugo'

docs_dir: 'docs'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  language: en
  include_sidebar: true
  favicon: img/logo.png
  logo: img/logo.png
  palette:
    primary: 'blue'
    accent: 'light blue'
  feature:
    tabs: false
  palette:
    primary: 'grey'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; Centrifugal"

extra_css:
  - theme/styles/extra.css
  - theme/styles/atom-one-light.css

extra_javascript:
  - theme/js/hljs/highlight.pack.js
  - theme/js/extra.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true

# Page tree
pages:
  - Getting Started: index.md
  - Basics: basics.md
  - Server:
    - 'Index': 'content/server/index.md'
